// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env } from 'prisma/config'

const isMigration = process.argv.some((arg) => arg.includes('migrate'))

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: isMigration ? env('DIRECT_URL') : env('DATABASE_URL'),
  },
})
