// domain/factories/index.ts
export { CitizenFactory } from './CitizenFactory'
export { JournalistFactory } from './JournalistFactory'
export { DirectorFactory } from './DirectorFactory'
export { ReportFactory } from './ReportFactory'
export { InvestigationFactory } from './InvestigationFactory'
export { InboxSubjectFactory } from './InboxSubjectFactory'
export { PublicationFactory } from './PublicationFactory'
export { NotificationFactory } from './NotificationFactory'
export { WatcherApplicationFactory } from './WatcherApplicationFactory'
export { EvidenceFactory } from './EvidenceFactory'
export { CorrectionFactory } from './CorrectionFactory'
export { AuthoritySourceFactory } from './AuthoritySourceFactory'
export { WorkflowAuditFactory } from './WorkflowAuditFactory'
