// domain/repositories/index.ts
export type { ICitizenRepository } from './ICitizenRepository'
export type { IJournalistRepository } from './IJournalistRepository'
export type { IDirectorRepository } from './IDirectorRepository'
export type { IInvestigationRepository } from './IInvestigationRepository'
export type { IReportRepository } from './IReportRepository'
export type { IReportMediaRepository } from './IReportMediaRepository'
export type { IEvidenceRepository } from './IEvidenceRepository'
export type { IInboxSubjectMediaRepository } from './IInboxSubjectMediaRepository'
export type { IInvestigationMediaRepository } from './IInvestigationMediaRepository'
export type { IInboxSubjectRepository } from './IInboxSubjectRepository'
export type { IPublicationRepository } from './IPublicationRepository'
export type { INotificationRepository } from './INotificationRepository'
export type { ICorrectionRepository } from './ICorrectionRepository'
export type { IWatcherApplicationRepository } from './IWatcherApplicationRepository'
export type { IAuthoritySourceRepository } from './IAuthoritySourceRepository'
export type { IWorkflowAuditRepository } from './IWorkflowAuditRepository'
